artifacts:
  javax_jms: org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1
  javax_ejb: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  activemq_core: org.apache.activemq:activemq-core:jar:5.3.2
  commons_logging: commons-logging:commons-logging:jar:1.1
  j2ee_management: org.apache.geronimo.specs:geronimo-j2ee-management_1.0_spec:jar:1.0

repositories:
  remote:
   - http://repo1.maven.org/maven2
