artifacts:
  jms: org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1
  activemq_core: org.apache.activemq:activemq-core:jar:5.3.2
  commons_logging: commons-logging:commons-logging:jar:1.1
  j2ee_management: org.apache.geronimo.specs:geronimo-j2ee-management_1.0_spec:jar:1.0

repositories:
  remote:
   - https://repository.apache.org/content/repositories/releases
   - http://repo1.maven.org/maven2
   - http://www.aQute.biz/repo
